import {
  Squares2X2Icon,
  CreditCardIcon,
  CurrencyDollarIcon,
  IdentificationIcon,
  WalletIcon,
  ServerIcon,
  ServerStackIcon,
  UsersIcon,
  ExclamationTriangleIcon,
  WifiIcon,
  CommandLineIcon,
  FlagIcon,
  CurrencyEuroIcon,
  ChartBarSquareIcon,
  BuildingLibraryIcon,
} from "@heroicons/vue/16/solid";

export default {
  Home: Squares2X2Icon,
  Invoices: CreditCardIcon,
  InvoicesTotal: CurrencyEuroIcon,
  InvoicesProblem: FlagIcon,
  Exchangers: CurrencyDollarIcon,
  Subscription: IdentificationIcon,
  Withdraws: WalletIcon,
  Services: ServerIcon,
  ServiceExchangers: ServerStackIcon,
  Employees: UsersIcon,
  Logs: ExclamationTriangleIcon,
  PhpLogs: CommandLineIcon,
  ApiLogs: WifiIcon,
  InvoicesLogs: CreditCardIcon,
  Stats: ChartBarSquareIcon,
  ExchangersStats: BuildingLibraryIcon,
};
